import { MembershipRole, Prisma, ProjectStatus } from '@prisma/client'
import { prisma } from '@/lib/db'
import { AppError } from '@/lib/errors'
import { requireOrganization, requireRole } from '@/lib/auth/guards'
import { createProjectSchema, updateProjectSchema, projectQuerySchema, createTaskSchema, updateTaskSchema, taskQuerySchema, taskIdSchema, duplicateTaskSchema, dependencySchema, commentSchema, commentUpdateSchema, subtaskSchema, activityQuerySchema } from '@/lib/validation/projects-tasks'

const canWrite = [MembershipRole.OWNER, MembershipRole.ADMIN, MembershipRole.MEMBER]
async function context(write = false) { return write ? requireRole(...canWrite) : requireOrganization() }
async function assertProject(id: string, organizationId: string) { const p = await prisma.project.findFirst({ where: { id, organizationId } }); if (!p) throw new AppError('NOT_FOUND', 'Project not found.', 404); return p }
async function assertTask(id: string, organizationId: string) { const t = await prisma.task.findFirst({ where: { id, organizationId } }); if (!t) throw new AppError('NOT_FOUND', 'Task not found.', 404); return t }
async function activity(tx: Prisma.TransactionClient, data: { organizationId: string; actorId: string; action: string; taskId?: string; projectId?: string; metadata?: Prisma.InputJsonValue }) { await tx.activityHistory.create({ data }) }

async function assertMembers(ids: string[], organizationId: string) { const memberships = await prisma.membership.findMany({ where: { organizationId, userId: { in: ids } }, select: { userId: true } }); if (new Set(memberships.map((m) => m.userId)).size !== new Set(ids).size) throw new AppError('VALIDATION', 'All project members must belong to this organization.', 400) }
export async function listProjects(input: unknown = {}) { const ctx = await context(); const q = projectQuerySchema.parse(input); return prisma.project.findMany({ where: { organizationId: ctx.organization.id, ...(q.includeArchived ? {} : { archivedAt: null }), ...(q.search ? { OR: [{ name: { contains: q.search, mode: 'insensitive' } }, { description: { contains: q.search, mode: 'insensitive' } }] } : {}), ...(q.status ? { status: q.status } : {}) }, orderBy: { [q.sort]: 'desc' }, include: { owner: { select: { id: true, name: true, avatarInitials: true } }, members: { include: { user: { select: { id: true, name: true, avatarInitials: true } } } }, _count: { select: { tasks: true } } } }) }
export async function createProject(input: unknown) { const ctx = await context(true); const data = createProjectSchema.parse(input); const memberIds = [...new Set([...(data.memberIds ?? []), data.ownerId ?? ctx.user.id])]; await assertMembers(memberIds, ctx.organization.id); return prisma.$transaction(async tx => { const { memberIds: _memberIds, ...projectData } = data; const p = await tx.project.create({ data: { ...projectData, organizationId: ctx.organization.id, creatorId: ctx.user.id, ownerId: data.ownerId ?? ctx.user.id, members: { create: memberIds.map((userId) => ({ organizationId: ctx.organization.id, userId })) } } }); await activity(tx, { organizationId: ctx.organization.id, actorId: ctx.user.id, projectId: p.id, action: 'project.created' }); return p }) }
export async function updateProject(input: unknown) { const ctx = await context(true); const data = updateProjectSchema.parse(input); await assertProject(data.id, ctx.organization.id); const memberIds = data.memberIds ? [...new Set(data.memberIds)] : undefined; if (memberIds) await assertMembers(memberIds, ctx.organization.id); const { id, memberIds: _memberIds, ...changes } = data; return prisma.$transaction(async tx => { if (memberIds) { await tx.projectMember.deleteMany({ where: { projectId: id } }); await tx.projectMember.createMany({ data: memberIds.map((userId) => ({ projectId: id, organizationId: ctx.organization.id, userId })) }) } const p = await tx.project.update({ where: { id }, data: changes }); await activity(tx, { organizationId: ctx.organization.id, actorId: ctx.user.id, projectId: id, action: 'project.updated', metadata: changes as Prisma.InputJsonValue }); return p }) }
export async function archiveProject(input: unknown) { const ctx = await context(true); const { id } = taskIdSchema.parse(input); await assertProject(id, ctx.organization.id); return prisma.$transaction(async tx => { const project = await tx.project.update({ where: { id }, data: { archivedAt: new Date(), status: ProjectStatus.ARCHIVED } }); await activity(tx, { organizationId: ctx.organization.id, actorId: ctx.user.id, projectId: id, action: 'project.archived' }); return project }) }
export async function deleteProject(input: unknown) { const ctx = await context(true); const { id } = taskIdSchema.parse(input); await assertProject(id, ctx.organization.id); return prisma.project.delete({ where: { id } }) }

export async function listTasks(input: unknown = {}) { const ctx = await context(); const q = taskQuerySchema.parse(input); return prisma.task.findMany({ where: { organizationId: ctx.organization.id, ...(q.includeArchived ? {} : { archivedAt: null }), ...(q.projectId ? { projectId: q.projectId } : {}), ...(q.status ? { status: q.status } : {}), ...(q.search ? { OR: [{ title: { contains: q.search, mode: 'insensitive' } }, { description: { contains: q.search, mode: 'insensitive' } }] } : {}) }, orderBy: [{ position: 'asc' }, { updatedAt: 'desc' }], include: { project: { select: { name: true } }, assignee: { select: { id: true, name: true, avatarInitials: true } }, comments: { orderBy: { createdAt: 'asc' }, include: { author: { select: { id: true, name: true, avatarInitials: true } } } }, subtasks: true, dependencies: true, dependents: true, activities: { orderBy: { createdAt: 'desc' }, take: 50 } } }) }
export async function createTask(input: unknown) { const ctx = await context(true); const data = createTaskSchema.parse(input); await assertProject(data.projectId, ctx.organization.id); if (data.assigneeId) await assertMembers([data.assigneeId], ctx.organization.id); const max = await prisma.task.aggregate({ where: { organizationId: ctx.organization.id, projectId: data.projectId }, _max: { position: true } }); return prisma.$transaction(async tx => { const t = await tx.task.create({ data: { ...data, organizationId: ctx.organization.id, creatorId: ctx.user.id, position: (max._max.position ?? 0) + 1 } }); await activity(tx, { organizationId: ctx.organization.id, actorId: ctx.user.id, taskId: t.id, projectId: t.projectId, action: 'task.created' }); return t }) }
export async function updateTask(input: unknown) { const ctx = await context(true); const data = updateTaskSchema.parse(input); const old = await assertTask(data.id, ctx.organization.id); if (data.projectId) await assertProject(data.projectId, ctx.organization.id); if (data.assigneeId) await assertMembers([data.assigneeId], ctx.organization.id); const { id, ...changes } = data; return prisma.$transaction(async tx => { const t = await tx.task.update({ where: { id }, data: changes }); await activity(tx, { organizationId: ctx.organization.id, actorId: ctx.user.id, taskId: id, projectId: t.projectId, action: 'task.updated', metadata: { before: { status: old.status }, changes } as Prisma.InputJsonValue }); return t }) }
export async function duplicateTask(input: unknown) { const ctx = await context(true); const data = duplicateTaskSchema.parse(input); const source = await assertTask(data.id, ctx.organization.id); const projectId = data.projectId ?? source.projectId; await assertProject(projectId, ctx.organization.id); return createTask({ projectId, title: `${source.title} (copy)`, description: source.description, priority: source.priority, labels: source.labels, dueAt: source.dueAt, estimatedMinutes: source.estimatedMinutes, assigneeId: source.assigneeId, parentId: source.parentId }) }
export async function deleteTask(input: unknown) { const ctx = await context(true); const { id } = taskIdSchema.parse(input); await assertTask(id, ctx.organization.id); return prisma.task.delete({ where: { id } }) }
export async function archiveTask(input: unknown) { const ctx = await context(true); const { id } = taskIdSchema.parse(input); const task = await assertTask(id, ctx.organization.id); return prisma.$transaction(async tx => { const result = await tx.task.update({ where: { id }, data: { archivedAt: new Date() } }); await activity(tx, { organizationId: ctx.organization.id, actorId: ctx.user.id, taskId: id, projectId: task.projectId, action: 'task.archived' }); return result }) }
export async function addTaskDependency(input: unknown) { const ctx = await context(true); const data = dependencySchema.parse(input); if (data.taskId === data.dependsOnId) throw new AppError('VALIDATION', 'A task cannot depend on itself.', 400); await assertTask(data.taskId, ctx.organization.id); await assertTask(data.dependsOnId, ctx.organization.id); return prisma.taskDependency.create({ data: { ...data, organizationId: ctx.organization.id } }) }
export async function removeTaskDependency(input: unknown) { const ctx = await context(true); const data = dependencySchema.parse(input); await prisma.taskDependency.deleteMany({ where: { ...data, organizationId: ctx.organization.id } }); return { ok: true } }
export async function addTaskComment(input: unknown) { const ctx = await context(true); const data = commentSchema.parse(input); const task = await assertTask(data.taskId, ctx.organization.id); return prisma.$transaction(async tx => { const comment = await tx.comment.create({ data: { ...data, organizationId: ctx.organization.id, authorId: ctx.user.id }, include: { author: { select: { id: true, name: true, avatarInitials: true } } } }); await activity(tx, { organizationId: ctx.organization.id, actorId: ctx.user.id, taskId: task.id, projectId: task.projectId, action: 'task.comment_added' }); return comment }) }
export async function updateTaskComment(input: unknown) { const ctx = await context(true); const data = commentUpdateSchema.parse(input); const comment = await prisma.comment.findFirst({ where: { id: data.id, taskId: data.taskId, organizationId: ctx.organization.id } }); if (!comment) throw new AppError('NOT_FOUND', 'Comment not found.', 404); if (comment.authorId !== ctx.user.id && ctx.membership.role !== MembershipRole.OWNER && ctx.membership.role !== MembershipRole.ADMIN) throw new AppError('FORBIDDEN', 'You can only edit your own comments.', 403); return prisma.comment.update({ where: { id: data.id }, data: { body: data.body } }) }
export async function deleteTaskComment(input: unknown) { const ctx = await context(true); const data = commentUpdateSchema.pick({ id: true, taskId: true }).parse(input); const comment = await prisma.comment.findFirst({ where: { id: data.id, taskId: data.taskId, organizationId: ctx.organization.id } }); if (!comment) throw new AppError('NOT_FOUND', 'Comment not found.', 404); if (comment.authorId !== ctx.user.id && ctx.membership.role !== MembershipRole.OWNER && ctx.membership.role !== MembershipRole.ADMIN) throw new AppError('FORBIDDEN', 'You can only delete your own comments.', 403); await prisma.comment.delete({ where: { id: data.id } }); return { ok: true } }
export async function createSubtask(input: unknown) { const ctx = await context(true); const data = subtaskSchema.parse(input); const parent = await assertTask(data.parentId, ctx.organization.id); await assertProject(data.projectId, ctx.organization.id); return prisma.$transaction(async tx => { const child = await tx.task.create({ data: { ...data, organizationId: ctx.organization.id, creatorId: ctx.user.id, position: 0 } }); await activity(tx, { organizationId: ctx.organization.id, actorId: ctx.user.id, taskId: parent.id, projectId: parent.projectId, action: 'task.subtask_created', metadata: { subtaskId: child.id } }); return child }) }
export async function completeSubtask(input: unknown) { const ctx = await context(true); const { id } = taskIdSchema.parse(input); const task = await assertTask(id, ctx.organization.id); return updateTask({ id: task.id, status: 'DONE' }) }
export async function deleteSubtask(input: unknown) { const ctx = await context(true); const { id } = taskIdSchema.parse(input); const task = await assertTask(id, ctx.organization.id); if (!task.parentId) throw new AppError('VALIDATION', 'Task is not a subtask.', 400); return deleteTask({ id }) }
export async function listTaskActivity(input: unknown) { const ctx = await context(); const query = activityQuerySchema.parse(input); if (query.taskId) await assertTask(query.taskId, ctx.organization.id); if (query.projectId) await assertProject(query.projectId, ctx.organization.id); return prisma.activityHistory.findMany({ where: { organizationId: ctx.organization.id, ...(query.taskId ? { taskId: query.taskId } : {}), ...(query.projectId ? { projectId: query.projectId } : {}) }, orderBy: { createdAt: 'desc' }, take: query.limit, include: { actor: { select: { id: true, name: true, avatarInitials: true } } } }) }
