'use client'

import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/workspace/automation-primitives'
import { createApiKeyAction, inviteMemberAction, listApiKeysAction, listAuditLogsAction, listNotificationsAction, markAllNotificationsReadAction, markNotificationReadAction, removeMemberAction, revokeApiKeyAction, updateMemberRoleAction } from '@/app/actions/platform'

type Member = { id: string; role: string; user: { id: string; name: string; email: string; avatarInitials: string | null } }
type Notification = { id: string; title: string; body: string; readAt: string | null; createdAt: string }
type ApiKey = { id: string; name: string; keyPrefix: string; createdAt: string }

export default function PlatformView({ kind, initialMembers = [], initialNotifications = [], initialApiKeys = [] }: { kind: 'Team' | 'Inbox' | 'API Keys' | 'Audit Logs'; initialMembers?: Member[]; initialNotifications?: Notification[]; initialApiKeys?: ApiKey[] }) {
  const [members, setMembers] = useState(initialMembers)
  const [notifications, setNotifications] = useState(initialNotifications)
  const [keys, setKeys] = useState(initialApiKeys)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [email, setEmail] = useState('')
  const [keyName, setKeyName] = useState('')
  const [secret, setSecret] = useState('')
  const [audit, setAudit] = useState<{ id: string; action: string; entityType: string; createdAt: string; actor: { name: string } | null }[]>([])
  useEffect(() => {
    if (kind === 'API Keys') void listApiKeysAction().then(result => { if ('ok' in result) setKeys(result.data as ApiKey[]) })
    if (kind === 'Inbox' && !initialNotifications.length) void listNotificationsAction().then(result => { if ('ok' in result) setNotifications(result.data as Notification[]) })
    if (kind === 'Audit Logs') void listAuditLogsAction().then(result => { if ('ok' in result) setAudit(result.data as typeof audit) })
  }, [kind, initialNotifications.length])
  const run = async (fn: () => Promise<{ ok: true; data: unknown } | { error: string }>, success: string) => { setBusy(true); setError(''); const result = await fn(); setBusy(false); if ('error' in result) setError(result.error); else setMessage(success) }
  if (kind === 'Team') return <div className="flex flex-col gap-6"><Section title="Team" description="Manage organization members and roles." /><Card><div className="flex gap-2"><input value={email} onChange={e => setEmail(e.target.value)} placeholder="member@example.com" className="flex-1 rounded-md border border-border bg-background px-3 py-2 text-sm" /><Button disabled={busy} onClick={() => void run(async () => { const result = await inviteMemberAction({ email, role: 'MEMBER' }); if ('ok' in result) setEmail(''); return result }, 'Invitation created.')}>Invite</Button></div><div className="mt-4 divide-y divide-border">{members.map(member => <div key={member.id} className="flex items-center gap-3 py-3 text-sm"><span className="flex-1">{member.user.name}<span className="ml-2 text-xs text-muted-foreground">{member.user.email}</span></span><select value={member.role} onChange={e => void run(async () => { const result = await updateMemberRoleAction({ userId: member.user.id, role: e.target.value }); if ('ok' in result) setMembers(items => items.map(item => item.id === member.id ? { ...item, role: e.target.value } : item)); return result }, 'Role updated.')} className="rounded border border-border bg-background px-2 py-1 text-xs">{['ADMIN', 'MANAGER', 'MEMBER', 'VIEWER'].map(role => <option key={role}>{role}</option>)}</select><button onClick={() => void run(async () => { const result = await removeMemberAction({ userId: member.user.id }); if ('ok' in result) setMembers(items => items.filter(item => item.id !== member.id)); return result }, 'Member removed.')} className="text-xs text-destructive">Remove</button></div>)}</div></Card><Feedback message={message} error={error}/></div>
  if (kind === 'Inbox') return <div className="flex flex-col gap-6"><Section title="Inbox" description="Notifications and updates for your organization." /><Card><div className="flex justify-end"><Button variant="outline" onClick={() => void run(async () => { const result = await markAllNotificationsReadAction(); if ('ok' in result) setNotifications(items => items.map(item => ({ ...item, readAt: new Date().toISOString() }))); return result }, 'All notifications marked read.')}>Mark all read</Button></div><div className="mt-3 divide-y divide-border">{notifications.map(item => <button key={item.id} onClick={() => void run(async () => { const result = await markNotificationReadAction({ id: item.id }); if ('ok' in result) setNotifications(items => items.map(notification => notification.id === item.id ? { ...notification, readAt: new Date().toISOString() } : notification)); return result }, 'Notification marked read.')} className={`block w-full py-3 text-left ${item.readAt ? 'opacity-60' : ''}`}><b className="text-sm">{item.title}</b><p className="text-xs text-muted-foreground">{item.body}</p></button>)}</div>{!notifications.length && <p className="py-8 text-center text-sm text-muted-foreground">No notifications.</p>}</Card><Feedback message={message} error={error}/></div>
  if (kind === 'API Keys') return <div className="flex flex-col gap-6"><Section title="API Keys" description="Manage organization access keys. Secrets are shown once." /><Card><div className="flex gap-2"><input value={keyName} onChange={e => setKeyName(e.target.value)} placeholder="Key name" className="flex-1 rounded-md border border-border bg-background px-3 py-2 text-sm" /><Button onClick={() => void run(async () => { const result = await createApiKeyAction({ name: keyName }); if ('ok' in result) { setKeys(items => [{ ...(result.data as ApiKey), keyPrefix: (result.data as { secret: string }).secret.slice(0, 12), createdAt: new Date().toISOString() }, ...items]); setSecret((result.data as { secret: string }).secret); setKeyName('') } return result }, 'API key created.')}>Create key</Button></div>{secret && <p className="mt-3 break-all rounded bg-muted p-2 text-xs">Copy this secret now: {secret}</p>}<div className="mt-4 divide-y divide-border">{keys.map(key => <div key={key.id} className="flex py-3 text-sm"><span className="flex-1">{key.name} <span className="text-xs text-muted-foreground">{key.keyPrefix}...</span></span><button onClick={() => void run(async () => { const result = await revokeApiKeyAction({ id: key.id }); if ('ok' in result) setKeys(items => items.filter(item => item.id !== key.id)); return result }, 'API key revoked.')} className="text-xs text-destructive">Revoke</button></div>)}</div></Card><Feedback message={message} error={error}/></div>
  return <div className="flex flex-col gap-6"><Section title="Audit Logs" description="Review organization security and administration activity." /><Card><Button variant="outline" onClick={() => void run(async () => { const result = await listAuditLogsAction(); if ('ok' in result) setAudit(result.data as typeof audit); return result }, 'Audit logs loaded.')}>Load logs</Button><div className="mt-4 divide-y divide-border">{audit.map(item => <div key={item.id} className="py-3 text-xs"><b>{item.action}</b> · {item.entityType}<span className="ml-2 text-muted-foreground">{item.actor?.name ?? 'System'} · {new Date(item.createdAt).toLocaleString()}</span></div>)}</div></Card><Feedback message={message} error={error}/></div>
}
function Section({ title, description }: { title: string; description: string }) { return <div><h2 className="text-2xl font-semibold tracking-tight">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div> }
function Feedback({ message, error }: { message: string; error: string }) { return <>{message && <p className="text-sm text-emerald-600">{message}</p>}{error && <p className="text-sm text-destructive">{error}</p>}</> }
